### ISSUE TITLE
Allow additional authorization method or callbacks?

### ISSUE THREAD

**Issue by azarus** [FilipLukac/passport-socketio-redis#1]
I see no way how to implement that so we can authorize sockets without passport.js

I would like to use socket.io with a thirdparty service that is going to push notifications into the web app. And for this i would like to setup an secret that the service can use.

**Comment by FilipLukac** [comment]
This is old and not maintained package. It works only with Passport.js - I published this package because I wanted to share our authentication process. I would like to recommend you to find something else that fits to you.

**Comment by azarus** [comment]
Then please update the readme or something. Actually this one was the most ease to use package that just worked fine with socketio & passport

**Comment by FilipLukac** [comment]
@azarus - updated readme - thank you.

**Comment by azarus** [comment]
Thanks, quite sad you no longer maintain this one took quite a while to get socket.io working properly with passport.js anyways thanks for sharing it :)
